### ISSUE TITLE
difere d'openExplorer

### ISSUE THREAD

**Issue by wilfried18** [BrandroidTools/Backbone#1]
I wanted to know if this application is better or worse than your https://github.com/BrandroidTools/OpenExplorer project and you have a web address to download the apk? for I know not use github to manufacture apk

**Comment by BrandoCommando** [comment]
Backbone is a different file manager project that a few other people and I were working on, but ultimately stopped. OpenExplorer is my personal project that I've been working off and on for about 3 or 4 years.

**Comment by wilfried18** [comment]
I do not know or tell you this but I have to create an article with video in French on this application
http://wilfriedcaruel.svnet.fr/2013/03/presentation-dopen-explorer-beta/

**Comment by BrandoCommando** [comment]
Thank you for taking the time to do this. We appreciate your support and
dedication. By the way, my real name is Brandon Bowles. :-)

**Comment by wilfried18** [comment]
tell me when the application is no longer in beta, I would do an article
